#!/bin/bash -x
# This is a simple build script and will be executed on your CI system if 
# available.  Otherwise it will execute while your application is stopped
# before the deploy step.  This script gets executed directly, so it
# could be python, php, ruby, etc.
echo "Entering build." | tee -a ${OPENSHIFT_PHP_LOG_DIR}/deploy.log
if [ -f ${OPENSHIFT_REPO_DIR}/php/config.php ]; then
    exit 0
fi
if [ ! -f ${OPENSHIFT_REPO_DIR}/php/config.php ]; then
    echo "Configuring TTRSS: Configuration" | tee -a ${OPENSHIFT_PHP_LOG_DIR}/deploy.log
    cp ${OPENSHIFT_REPO_DIR}/misc/config.php ${OPENSHIFT_REPO_DIR}/php/config.php
else
    echo "***WARNING***: Be sure to update \$OPENSHIFT_REPO_DIR/php/config.php with content" | tee -a ${OPENSHIFT_PHP_LOG_DIR}/deploy.log
    echo "***WARNING***: from \$OPENSHIFT_REPO_DIR/misc/config.php" | tee -a ${OPENSHIFT_PHP_LOG_DIR}/deploy.log
fi

# Set up various cache directories
if [ ! -d ${OPENSHIFT_DATA_DIR}/ttrss ]; then
  echo "Configuring tt-rss cache directories"| tee -a ${OPENSHIFT_PHP_LOG_DIR}/deploy.log
  mkdir -p ${OPENSHIFT_DATA_DIR}/ttrss
  cp -r ${OPENSHIFT_REPO_DIR}/php/{cache,lock} ${OPENSHIFT_DATA_DIR}/ttrss/
  mv ${OPENSHIFT_REPO_DIR}/php/feed-icons ${OPENSHIFT_DATA_DIR}/ttrss/
else
  rm -rf ${OPENSHIFT_REPO_DIR}/php/feed-icons
fi
ln -sf ${OPENSHIFT_DATA_DIR}/ttrss/feed-icons ${OPENSHIFT_REPO_DIR}/php/feed-icons

# Set up sphinx full-text search
if [ ! -d ${OPENSHIFT_DATA_DIR}/run ]; then
  echo "Configuring Sphinx: Directories" | tee -a ${OPENSHIFT_PHP_LOG_DIR}/deploy.log
  mkdir -p ${OPENSHIFT_DATA_DIR}/run
  mkdir -p ${OPENSHIFT_DATA_DIR}/sphinx/var/data
  mkdir -p ${OPENSHIFT_DATA_DIR}/sphinx/etc
fi
# Configure sphinx for current instance
echo "Configuring Sphinx: Configuration" | tee -a ${OPENSHIFT_PHP_LOG_DIR}/deploy.log
${OPENSHIFT_REPO_DIR}/misc/sed-sphinx.sh > ${OPENSHIFT_DATA_DIR}/sphinx/etc/sphinx.conf

echo "Leaving build." | tee -a ${OPENSHIFT_PHP_LOG_DIR}/deploy.log
exit 0
