#!/bin/bash -ex
# Deploy: Just before starting the application
echo "Entering deploy." | tee -a ${OPENSHIFT_PHP_LOG_DIR}/deploy.log

# Ensure db exists
if [ ${OPENSHIFT_POSTGRESQL_DB_HOST}"x" == "x"]; then
	echo "Database environment not set!" | tee -a ${OPENSHIFT_PHP_LOG_DIR}/deploy.log
	exit 0
fi

if [ -f ${OPENSHIFT_DATA_DIR}/.schema_deployed ]; then 
    echo "Schema already deployed." | tee -a ${OPENSHIFT_PHP_LOG_DIR}/deploy.log
else 
    echo "Deploying database schema." | tee -a ${OPENSHIFT_PHP_LOG_DIR}/deploy.log
    psql -h${OPENSHIFT_POSTGRESQL_DB_HOST} -U${OPENSHIFT_POSTGRESQL_DB_USERNAME} ${WOPENSHIFT_POSTGRESQL_DB_PASSWORD} -f${OPENSHIFT_REPO_DIR}/php/schema/ttrss_schema_pgsql.sql ${OPENSHIFT_APP_NAME} || exit 1
    date >> ${OPENSHIFT_DATA_DIR}/.schema_deployed
    echo "Schema deployed successfully." | tee -a ${OPENSHIFT_PHP_LOG_DIR}/deploy.log
fi

# Initialize the search repo
echo "Creating/updating search repositories." | tee -a ${OPENSHIFT_PHP_LOG_DIR}/deploy.log
${OPENSHIFT_REPO_DIR}/.openshift/cron/daily/sphinx
${OPENSHIFT_REPO_DIR}/.openshift/cron/hourly/sphinx
exit 0
