#!/bin/bash
# This is a simple post deploy hook executed after your application 
# is deployed and started.  This script gets executed directly, so 
# it could be python, php, ruby, etc.

if [ -f ${OPENSHIFT_DATA_DIR}/.schema_deployed ]; then 
    echo "Schema already deployed."
else 
    psql -h${OPENSHIFT_POSTGRESQL_DB_HOST} -U${OPENSHIFT_POSTGRESQL_DB_USERNAME} ${WOPENSHIFT_POSTGRESQL_DB_PASSWORD} -f${OPENSHIFT_REPO_DIR}/php/schema/ttrss_schema_pgsql.sql ${OPENSHIFT_APP_NAME} || exit 1
    date >> ${OPENSHIFT_DATA_DIR}/.schema_deployed
    echo "Schema deployed successfully."
fi
# Start the sphinx daemon
# Make sure it gets seeded with some data
${OPENSHIFT_REPO_DIR}/sphinx/bin/indexer --rotate --config ${OPENSHIFT_DATA_DIR}/sphinx/etc/sphinx.conf ${OPENSHIFT_APP_NAME} 
${OPENSHIFT_REPO_DIR}/sphinx/bin/searchd --config ${OPENSHIFT_DATA_DIR}/sphinx/etc/sphinx.conf --stop
${OPENSHIFT_REPO_DIR}/sphinx/bin/searchd --config ${OPENSHIFT_DATA_DIR}/sphinx/etc/sphinx.conf 
