#!/bin/bash -x
# This is a simple post deploy hook executed after your application 
# is deployed and started.  This script gets executed directly, so 
# it could be python, php, ruby, etc.

echo "Entering post-deploy" | tee -a ${OPENSHIFT_PHP_LOG_DIR}/deploy.log

# Ensure db exists
if [ -z ${OPENSHIFT_POSTGRESQL_DB_HOST} ]; then
	echo "Database environment not set!" | tee -a ${OPENSHIFT_PHP_LOG_DIR}/deploy.log
	exit 0
fi

if [ -f ${OPENSHIFT_DATA_DIR}/.schema_deployed ]; then 
    echo "Schema already deployed." | tee -a ${OPENSHIFT_PHP_LOG_DIR}/deploy.log
else 
    echo "Creating database." | tee -a ${OPENSHIFT_PHP_LOG_DIR}/deploy.log
    createdb -w ${OPENSHIFT_APP_NAME}
    echo "Deploying database schema." | tee -a ${OPENSHIFT_PHP_LOG_DIR}/deploy.log
    psql -w -f ${OPENSHIFT_REPO_DIR}/php/schema/ttrss_schema_pgsql.sql ${OPENSHIFT_APP_NAME} && \
    date >> ${OPENSHIFT_DATA_DIR}/.schema_deployed && \
    echo "Schema deployed successfully." | tee -a ${OPENSHIFT_PHP_LOG_DIR}/deploy.log
fi

echo "Updating sphinx." | tee -a ${OPENSHIFT_PHP_LOG_DIR}/deploy.log
# Set up sphinx full-text search
if [ ! -d ${OPENSHIFT_DATA_DIR}/run ]; then
  echo "***ERROR***: Should have completed during deploy hook."
  echo "Configuring Sphinx: Directories" | tee -a ${OPENSHIFT_PHP_LOG_DIR}/deploy.log
  mkdir -p ${OPENSHIFT_DATA_DIR}/run
  mkdir -p ${OPENSHIFT_DATA_DIR}/sphinx/var/data
  mkdir -p ${OPENSHIFT_DATA_DIR}/sphinx/etc
  # Configure sphinx for current instance
  echo "Configuring Sphinx: Configuration" | tee -a ${OPENSHIFT_PHP_LOG_DIR}/deploy.log
  ${OPENSHIFT_REPO_DIR}/misc/sed-sphinx.sh > ${OPENSHIFT_DATA_DIR}/sphinx/etc/sphinx.conf
fi

# Update the feeds to get some initial data
${OPENSHIFT_REPO_DIR}/.openshift/cron/minutely/update-feeds

echo "Starting sphinx." | tee -a ${OPENSHIFT_PHP_LOG_DIR}/deploy.log
${OPENSHIFT_REPO_DIR}/misc/sphinx.sh restart 

echo "Starting Indexer" | tee -a ${OPENSHIFT_PHP_LOG_DIR}/deploy.log
${OPENSHIFT_REPO_DIR}/sphinx/bin/indexer --rotate --config ${OPENSHIFT_DATA_DIR}/sphinx/etc/sphinx.conf ${OPENSHIFT_APP_NAME} 
echo "Leaving post-deploy" | tee -a ${OPENSHIFT_PHP_LOG_DIR}/deploy.log
exit 0
